services:
  kafka:
    image: confluentinc/cp-kafka:7.4.1
    # Running Kafka in single-node KRaft mode (no ZooKeeper) for local development
    # and testing. This is NOT a production multi-broker configuration. 
    # Confluent's image requires CLUSTER_ID in base64 (16 bytes, no '=' padding).
    # Generate one with: 
    #   $ python3 -c "import base64,os; print(base64.b64encode(os.urandom(16)).decode().rstrip('='))"
    environment:
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1"
      KAFKA_CLUSTER_ID: "Vi3Vdi4sf0h38zVbEgqQ6w" # for compatibility
      CLUSTER_ID: "Vi3Vdi4sf0h38zVbEgqQ6w"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092" # internal: containers use kafka:9092
      - "9094:9094" # external: host tools use localhost:9094
    networks:
      - internal

networks:
  internal:
    external: true
    name: ${DOCKER_NETWORK_NAME:-internal}
